name: Generate docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
       pip3 install -r requirements.txt
       sudo apt-get install doxygen clang-format -y
      

    - name: Generate files
      run: python3 generate.py

    - name: Generate Doxygen Documentation
      run: doxygen
      shell: bash

    - name: Create .nojekyll
      run: touch docs/html/.nojekyll
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{ inputs.github_token }}
        branch: gh-pages
        folder: docs/html